### ISSUE TITLE
Bug: gf-wabapp: map object description is not translated

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/goldenFleece#102]
Steps to reproduce

1. Openg gf-webapp main page
2. Press on item in the map menu list (Open right block with object description)
3. Change language
4. Pay attention to object description

Actual result: description isn't translated
Expected: description is translated

Estimation
(40h)

**Comment by Ekaterina1994** [comment]
Done.
Estimation: 8h (without styling blocks)
