### ISSUE TITLE
Bug: gf-webapp map zoom

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/goldenFleece#103]
Steps to reproduce

1. Openg gf-webapp main page
2. Pay attention on edge content of map. (for example on the bottom)
3. Zoom in map.
4. Scroll to the edge of the map (for example to the bottom)

Actual result: edge content partly not visible (not accessible) 
Expected: all map content accessible and could be visible 

Estimation:
(24h)

**Comment by Ekaterina1994** [comment]
Closed because of connectinf map by Leaflet
